#!/bin/bash

export STUDYMULTDIR=$PWD
export FASTJETDIR="/afs/cern.ch/work/c/cmcginn/public/Fastjet/fastjet-install"
export STUDYPYTPATH="/afs/cern.ch/work/c/cmcginn/public/Packages/PYTHIA8/pythia8230"

echo "SETTING NEW ENVIRONMENT VARIABLE STUDYMULTDIR AS '$PWD'"
echo "SETTING NEW ENVIRONMENT VARIABLE FASTJETDIR AS '$FASTJETDIR'"
echo "   !!!IF YOU ARE NOT ON LXPLUS, PLEASE POINT FASTJETDIR TO YOUR OWN FASTJET INSTALL!!!"
echo "SETTING NEW ENVIRONMENT VARIABLE STUDYPYTPATH AS '$STUDYPYTPATH'"
echo "   !!!IF YOU ARE NOT ON LXPLUS, PLEASE POINT STUDYPYTPATH TO YOUR OWN FASTJET INSTALL!!!"
echo ""

echo "All environment variables set"